version: '3.7'

volumes:
  db-data:

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: db_ordering_tool
      MYSQL_ROOT_PASSWORD: db%&secret
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./orderingToolServer/
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_ordering_tool?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: db%&secret
      SPRING_PROFILES_ACTIVE: prod
      TZ: CET

  frontend:
    build: ./app/
    ports:
      - 4200:80

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80