INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_FIRSTNAME) VALUES (1, 'Meier', 'Robert');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_FIRSTNAME) VALUES (2, 'Keller', 'Tobias');

INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, CUSTOMER_ID, DRY_WEIGHT_KG) VALUES (1, '2022-02-28', 1, 4);
INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, CUSTOMER_ID, DRY_WEIGHT_KG) VALUES (2, '2022-02-28', 2, 4);