INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_FIRSTNAME) VALUES (1, 'Meier', 'Robert');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_FIRSTNAME) VALUES (2, 'Keller', 'Tobias');

INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, CUSTOMER_ID) VALUES (1, '2022-02-28', 1);